# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.20
_src_path: git@github.com:OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Odoo
odoo_version: 16.0
org_name: Open Net Sàrl
org_slug: mycityco2
rebel_module_groups: []
repo_description: Base module to track CO2 equivalent in accounting
repo_name: Base module to track CO2 equivalent in accounting
repo_slug: mycityco2-engine
repo_website: https://www.open-net.ch
use_pyproject_toml: true
use_ruff: true

