from unittest.mock import MagicMock, patch

from odoo.tests import tagged

from odoo.addons.sustainability_stock.tests.common import CarbonCommon


@tagged("test_stock_freight")
class TestStockFreightPickingTypes(CarbonCommon):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()

        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_response.json.return_value = {
            "co2e": 10,
            "co2e_unit": "kg",
            "route": [
                {
                    "type": "leg",
                    "co2e": 10,
                    "co2e_unit": "kg",
                    "source_trail": [
                        {
                            "data_category": "emission_factor",
                            "name": "Articulated truck <34t - Average/mixed load - Diesel",
                            "source": "GLEC",
                            "source_dataset": "Default fuel efficiency and GHG emission intensity values v3.0",
                            "year": "2023",
                            "region": "EU_S_AMERICA",
                            "region_name": "Europe and South America",
                        }
                    ],
                    "transport_mode": "road",
                }
            ],
        }

        cls._patch_post = patch("requests.post", return_value=mock_response)
        cls._patch_post.start()

    @classmethod
    def tearDownClass(cls):
        cls._patch_post.stop()
        super().tearDownClass()

    def test_computation(self):
        """Test computation on both incoming and outgoing pickings"""
        incoming_carbon_line_origins = self.env["carbon.line.origin"].search(
            [("move_carbon_freight_picking_id", "=", self.incoming_picking.id)]
        )
        incoming_total_value = sum(
            origin.signed_value for origin in incoming_carbon_line_origins
        )

        outgoing_carbon_line_origins = self.env["carbon.line.origin"].search(
            [("move_carbon_freight_picking_id", "=", self.outgoing_picking.id)]
        )
        outgoing_total_value = sum(
            origin.signed_value for origin in outgoing_carbon_line_origins
        )

        expected_result = 10

        self.assertEqual(
            round(incoming_total_value, 2),
            expected_result,
            f"Incoming picking: Expected a carbon value of {expected_result}, got {round(incoming_total_value, 2)}",
        )
        self.assertEqual(
            round(outgoing_total_value, 2),
            expected_result,
            f"Outgoing picking: Expected a carbon value of {expected_result}, got {round(outgoing_total_value, 2)}",
        )

        self.assertEqual(
            round(self.incoming_picking.carbon_debt, 2),
            expected_result,
            "Carbon debt not correctly stored on incoming picking",
        )
        self.assertEqual(
            round(self.outgoing_picking.carbon_debt, 2),
            expected_result,
            "Carbon debt not correctly stored on outgoing picking",
        )

    def test_picking_action(self):
        """Test the actions of the smart buttons that link to the carbon origins generated by the carbon computation"""
        incoming_action = self.incoming_picking.action_see_carbon_origins()
        self.assertEqual(incoming_action["res_model"], "carbon.line.origin")
        self.assertEqual(
            incoming_action["name"],
            f"Carbon Footprint for {self.incoming_picking.name}",
        )
        self.assertEqual(
            incoming_action["domain"],
            [("move_carbon_freight_picking_id", "=", self.incoming_picking.id)],
        )

        outgoing_action = self.outgoing_picking.action_see_carbon_origins()
        self.assertEqual(outgoing_action["res_model"], "carbon.line.origin")
        self.assertEqual(
            outgoing_action["name"],
            f"Carbon Footprint for {self.outgoing_picking.name}",
        )
        self.assertEqual(
            outgoing_action["domain"],
            [("move_carbon_freight_picking_id", "=", self.outgoing_picking.id)],
        )

    def test_incoming_picking_carbon_product(self):
        """Test that incoming pickings use the upstream carbon product"""
        account_move = self.env["account.move"].search(
            [("carbon_freight_picking_id", "=", self.incoming_picking.id)], limit=1
        )

        self.assertTrue(
            account_move, "No account move was created for the incoming picking"
        )

        product_line = account_move.line_ids.filtered(lambda line: line.product_id)
        self.assertEqual(
            product_line.product_id,
            self.env.company.carbon_freight_product_upstream,
            "Incoming picking should use the upstream carbon product",
        )
        self.assertIn(
            "Upstream",
            account_move.ref,
            "Account move reference should mention Upstream",
        )

    def test_outgoing_picking_carbon_product(self):
        """Test that outgoing pickings use the downstream carbon product"""

        account_move = self.env["account.move"].search(
            [("carbon_freight_picking_id", "=", self.outgoing_picking.id)], limit=1
        )

        self.assertTrue(
            account_move, "No account move was created for the outgoing picking"
        )

        product_line = account_move.line_ids.filtered(lambda line: line.product_id)
        self.assertEqual(
            product_line.product_id,
            self.env.company.carbon_freight_product_downstream,
            "Outgoing picking should use the downstream carbon product",
        )
        self.assertIn(
            "Downstream",
            account_move.ref,
            "Account move reference should mention Downstream",
        )

    def test_picking_type_detection(self):
        """Test the correct detection of picking types for carbon emissions calculation"""
        self.assertEqual(
            self.incoming_picking.picking_type_id.code,
            "incoming",
            "Purchase order picking should be of type 'incoming'",
        )
        self.assertEqual(
            self.outgoing_picking.picking_type_id.code,
            "outgoing",
            "Sale order picking should be of type 'outgoing'",
        )

        is_inbound_receipt_incoming = (
            self.incoming_picking.picking_type_id.code == "incoming"
        )
        is_inbound_receipt_outgoing = (
            self.outgoing_picking.picking_type_id.code == "incoming"
        )

        self.assertTrue(
            is_inbound_receipt_incoming,
            "Incoming picking should be detected as inbound receipt",
        )
        self.assertFalse(
            is_inbound_receipt_outgoing,
            "Outgoing picking should not be detected as inbound receipt",
        )

    def test_freight_computation(self):
        """Test the creation of freight computation instance serving as a cache to avoid re-calling the API"""
        picking = self.incoming_picking
        origin = picking._get_address_inline(
            picking.picking_type_id.warehouse_id.partner_id._display_address(
                without_company=True
            )
        )
        destination = picking._get_address_inline(
            picking.partner_id._display_address(without_company=True)
        )
        weight = picking.shipping_weight
        transport_mode = self.env.company.carbon_freight_transport_mode
        units = ("kg", "lb")
        unit_select_id = int(
            self.env["ir.config_parameter"].sudo().get_param("product.weight_in_lbs")
        )
        weight_unit = units[unit_select_id]

        existing_computation = self.env[
            "sustainability.stock.freight.computation"
        ].search(
            [
                ("origin", "=", origin),
                ("destination", "=", destination),
                ("weight_unit", "=", weight_unit),
                ("transport_mode", "=", transport_mode),
                (
                    "co2_ratio",
                    "=",
                    self.incoming_picking.carbon_debt / weight if weight else 0,
                ),
            ],
            limit=1,
        )
        self.assertTrue(existing_computation)
