from . import res_company
from . import res_config_settings
from . import stock_picking
from . import account_move
from . import carbon_line_origin
from . import carbon_line_mixin
from . import sustainability_stock_freight_computation
from . import res_partner
from . import carbon_factor
