name: update_pot

on:
  push:
    branches:
      - "16.0"

jobs:
  update_pot:
    runs-on: ubuntu-22.04
    container: ${{ matrix.container }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: ghcr.io/oca/oca-ci/py3.10-odoo16.0:latest
            name: update pot file
            makepot: "true"
    services:
      postgres:
        image: postgres:12.0
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
    env:
      OCA_GIT_USER_EMAIL: info@mycompanyco2.org
      OCA_GIT_USER_NAME: sustainabilitybot
    steps:
      - name: Update .pot files
        run: oca_export_and_push_pot https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        if: ${{ matrix.makepot == 'true' && github.event_name == 'push' && github.repository_owner == 'sustainability-suite' }}
