[project]
name = "odoo-addons-sustainability-suite-sustainability-odoo"
version = "18.0.20250918.0"
dependencies = [
    "odoo-addon-sustainability==18.0.*",
    "odoo-addon-sustainability_employee_commuting==18.0.*",
    "odoo-addon-sustainability_hr_expense_report==18.0.*",
    "odoo-addon-sustainability_mis_builder==18.0.*",
    "odoo-addon-sustainability_point_of_sale==18.0.*",
    "odoo-addon-sustainability_product_label_print==18.0.*",
    "odoo-addon-sustainability_purchase==18.0.*",
    "odoo-addon-sustainability_purchase_stock==18.0.*",
    "odoo-addon-sustainability_sale==18.0.*",
    "odoo-addon-sustainability_spreadsheet_dashboard==18.0.*",
    "odoo-addon-sustainability_stock==18.0.*",
    "odoo-addon-sustainability_website_sale==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
